name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint-test-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # full history for SonarCloud
      - uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Lint and format
        run: pnpm run ci:lint-format

      - name: Build packages
        run: pnpm run ci:build

      - name: Chromatic
        if: github.actor != 'dependabot[bot]'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: documentation
          exitOnceUploaded: true
          autoAcceptChanges: true

      - name: Type check
        run: pnpm run type-check

      - name: Run coverage
        run: pnpm run coverage

      - name: Check if audit and sonar scans are needed (can be skipped for only tokens/icons changes)
        id: check-changes
        run: |
          if [ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" ] || git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -qvE '^packages/styles/src/(tokens|img)/'; then
            echo "run-full-checks=true" >> $GITHUB_OUTPUT
          else
            echo "run-full-checks=false" >> $GITHUB_OUTPUT
          fi

      # audit is skipped if only tokens or icons are changed
      - name: Audit
        if: steps.check-changes.outputs.run-full-checks == 'true'
        run: pnpm run audit

      - name: Sonar scan
        if: steps.check-changes.outputs.run-full-checks == 'true' && github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
